Traceback (most recent call last):
  File "test_params.py", line 2, in <module>
    import timei
ImportError: No module named timei
No handlers could be found for logger "bash_command.pyc"
mkdir /home/judah/archive/1


mkdir /home/judah/archive/1/lm


/home/judah/irstlm-5.80.03/bin/add-start-end.sh < /home/judah/corpus/kde4.es-en.true.es > /home/judah/archive/1/lm/kde4.es-en.sb.es


/home/judah/irstlm-5.80.03/bin/build-lm.sh -i /home/judah/archive/1/lm/kde4.es-en.sb.es -t /home/judah/archive/1/lm/tmp -p -n 3 -s improved-kneser-ney -o /home/judah/archive/1/lm/kde4.es-en.ilm.es.gz
Set IRSTLM environment variable with path to irstlm

Traceback (most recent call last):
  File "test_params.py", line 141, in <module>
    main()
  File "test_params.py", line 135, in main
    run_config(c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7], c[8],1)
  File "test_params.py", line 94, in run_config
    pcommand("{0}/bin/build-lm.sh -i {5}/{1}.sb.{4} -t {5}/tmp -p -n {2} -s {3} -o {5}/{1}.ilm.{4}.gz".format(irstlm_path,train_name, l_order, l_smoothing, foreign, lm_path))
  File "test_params.py", line 33, in pcommand
    o=command(c)
  File "/home/judah/doctrans/demo/bash_command.py", line 65, in command
    raise CommandError(m)
bash_command.CommandError: /home/judah/irstlm-5.80.03/bin/build-lm.sh -i /home/judah/archive/1/lm/kde4.es-en.sb.es -t /home/judah/archive/1/lm/tmp -p -n 3 -s improved-kneser-ney -o /home/judah/archive/1/lm/kde4.es-en.ilm.es.gz returned 2
No handlers could be found for logger "bash_command.pyc"
Traceback (most recent call last):
  File "test_params.py", line 177, in <module>
    main()
  File "test_params.py", line 167, in main
    pool_outputs = pool.map(run_star, config)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
bash_command.CommandError: /home/judah/irstlm-5.80.03/bin/build-lm.sh -i /home/judah/archive/4/lm/kde4.es-en.sb.es -t /home/judah/archive/4/lm/tmp -p -n 3 -s improved-kneser-ney -o /home/judah/archive/4/lm/kde4.es-en.ilm.es.gz returned 2


Set IRSTLM environment variable with path to irstlm

No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
Traceback (most recent call last):
  File "test_params.py", line 177, in <module>
    main()
  File "test_params.py", line 167, in main
    pool_outputs = pool.map(run_star, config)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
bash_command.CommandError: mkdir /home/judah/archive/13 returned 1

mkdir: cannot create directory ‘/home/judah/archive/1’: File exists

mkdir: cannot create directory ‘/home/judah/archive/9’: File exists

mkdir: cannot create directory ‘/home/judah/archive/12’: File exists

mkdir: cannot create directory ‘/home/judah/archive/3’: File exists

mkdir: cannot create directory ‘/home/judah/archive/10’: File exists

mkdir: cannot create directory ‘/home/judah/archive/2’: File exists

mkdir: cannot create directory ‘/home/judah/archive/6’: File exists

mkdir: cannot create directory ‘/home/judah/archive/4’: File exists

mkdir: cannot create directory ‘/home/judah/archive/5’: File exists

mkdir: cannot create directory ‘/home/judah/archive/19’: File exists

mkdir: cannot create directory ‘/home/judah/archive/16’: File exists

mkdir: cannot create directory ‘/home/judah/archive/13’: File exists

mkdir: cannot create directory ‘/home/judah/archive/20’: File exists

mkdir: cannot create directory ‘/home/judah/archive/11’: File exists

mkdir: cannot create directory ‘/home/judah/archive/7’: File exists

mkdir: cannot create directory ‘/home/judah/archive/17’: File exists

mkdir: cannot create directory ‘/home/judah/archive/22’: File exists

mkdir: cannot create directory ‘/home/judah/archive/8’: File exists

mkdir: cannot create directory ‘/home/judah/archive/21’: File exists

mkdir: cannot create directory ‘/home/judah/archive/14’: File exists

mkdir: cannot create directory ‘/home/judah/archive/15’: File exists

mkdir: cannot create directory ‘/home/judah/archive/0’: File exists

mkdir: cannot create directory ‘/home/judah/archive/23’: File exists

mkdir: cannot create directory ‘/home/judah/archive/18’: File exists
No handlers could be found for logger "bash_command.pyc"
Traceback (most recent call last):
  File "test_params.py", line 177, in <module>
    main()
  File "test_params.py", line 167, in main
    pool_outputs = pool.map(run_star, config)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
bash_command.CommandError: /home/judah/irstlm-5.80.03/bin/build-lm.sh -i /home/judah/archive/21/lm/kde4.es-en.sb.es -t /home/judah/archive/21/lm/tmp -p -n 3 -s witten-bell -o /home/judah/archive/21/lm/kde4.es-en.ilm.es.gz returned 2


Set IRSTLM environment variable with path to irstlm

No handlers could be found for logger "bash_command.pyc"
Traceback (most recent call last):
  File "test_params.py", line 178, in <module>
    main()
  File "test_params.py", line 168, in main
    pool_outputs = pool.map(run_star, config)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
bash_command.CommandError: /home/judah/irstlm-5.80.03/bin/build-lm.sh -i /home/judah/archive/23/lm/kde4.es-en.sb.es -t /home/judah/archive/23/lm/tmp -p -n 3 -s witten-bell -o /home/judah/archive/23/lm/kde4.es-en.ilm.es.gz returned 2


Set IRSTLM environment variable with path to irstlm

Traceback (most recent call last):
  File "test_params.py", line 178, in <module>
    main()
  File "test_params.py", line 154, in main
    os.environ['IRSTLM'] = irstlm_path
NameError: global name 'os' is not defined


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
No handlers could be found for logger "bash_command.pyc"
Traceback (most recent call last):
  File "test_params.py", line 183, in <module>
    main()
  File "test_params.py", line 173, in main
    pool_outputs = pool.map(run_star, config)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
bash_command.CommandError: mkdir /home/judah/archive/1 returned 1

mkdir: cannot create directory ‘/home/judah/archive/29’: File exists

mkdir: cannot create directory ‘/home/judah/archive/10’: File exists

mkdir: cannot create directory ‘/home/judah/archive/11’: File exists

mkdir: cannot create directory ‘/home/judah/archive/7’: File exists

mkdir: cannot create directory ‘/home/judah/archive/16’: File exists

mkdir: cannot create directory ‘/home/judah/archive/2’: File exists

mkdir: cannot create directory ‘/home/judah/archive/3’: File exists

mkdir: cannot create directory ‘/home/judah/archive/4’: File exists

mkdir: cannot create directory ‘/home/judah/archive/0’: File exists

mkdir: cannot create directory ‘/home/judah/archive/9’: File exists

mkdir: cannot create directory ‘/home/judah/archive/17’: File exists

mkdir: cannot create directory ‘/home/judah/archive/12’: File exists

mkdir: cannot create directory ‘/home/judah/archive/1’: File exists

mkdir: cannot create directory ‘/home/judah/archive/27’: File exists

mkdir: cannot create directory ‘/home/judah/archive/5’: File exists

mkdir: cannot create directory ‘/home/judah/archive/25’: File exists

mkdir: cannot create directory ‘/home/judah/archive/28’: File exists

mkdir: cannot create directory ‘/home/judah/archive/13’: File exists

mkdir: cannot create directory ‘/home/judah/archive/23’: File exists

mkdir: cannot create directory ‘/home/judah/archive/18’: File exists

mkdir: cannot create directory ‘/home/judah/archive/22’: File exists

mkdir: cannot create directory ‘/home/judah/archive/26’: File exists

mkdir: cannot create directory ‘/home/judah/archive/19’: File exists

mkdir: cannot create directory ‘/home/judah/archive/20’: File exists

mkdir: cannot create directory ‘/home/judah/archive/21’: File exists
Traceback (most recent call last):
  File "test_params.py", line 32, in <module>
    log_file=open("{0}/LOG.txt".format(archive_path), "w", 1)
IOError: [Errno 2] No such file or directory: '/home/judah/archive/LOG.txt'


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested


trained
tuned
tested
No handlers could be found for logger "bash_command.pyc"
Traceback (most recent call last):
  File "test_params.py", line 185, in <module>
    main()
  File "test_params.py", line 174, in main
    pool_outputs = pool.map(run_star, config)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
bash_command.CommandError: /home/judah/mosesdecoder/bin/build_binary /home/judah/archive3/61/lm/kde4.es-en.arpa.es /home/judah/archive3/61/lm/kde4.es-en.blm.es returned 1



Reading /home/judah/archive3/61/lm/kde4.es-en.arpa.es
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
lm/read_arpa.cc:151 in void lm::PositiveProbWarn::Warn(float) threw FormatLoadException'.
Positive log probability 3.16534e-07 in the model.  This is a bug in IRSTLM; you can set config.positive_log_probability = SILENT or pass -i to build_binary to substitute 0.0 for the log probability.  Error in the 4-gram at byte 24225679 Byte: 24225679
ERROR
